"""JSON-backed secrets store with optional ``/etc/hosaka/env`` mirror.

Design constraints:

* Atomic writes (``tmp + os.replace``) so a crash mid-write can't
  truncate the file.
* Strict permissions: ``0o600`` on the JSON, ``0o640`` on the env file
  (root-owned, ``operator`` group readable so the systemd unit running
  as ``operator`` can pick it up).
* Mirroring to ``/etc/hosaka/env`` is best-effort — when the current
  process can't write there (the common case for non-root callers) we
  return a structured ``MirrorSkipped`` and the CLI tells the operator
  the exact ``sudo`` line to run.
"""
from __future__ import annotations

import json
import logging
import os
import shlex
import tempfile
from dataclasses import dataclass
from pathlib import Path

log = logging.getLogger("hosaka.secrets.store")

JSON_PATH_ENV = "HOSAKA_SECRETS_PATH"
ENV_PATH_ENV = "HOSAKA_ENV_FILE"

DEFAULT_JSON_PATH = Path.home() / ".hosaka" / "secrets.json"
DEFAULT_ENV_PATH = Path("/etc/hosaka/env")


def json_path() -> Path:
    raw = os.getenv(JSON_PATH_ENV, "").strip()
    return Path(raw).expanduser() if raw else DEFAULT_JSON_PATH


def env_path() -> Path:
    raw = os.getenv(ENV_PATH_ENV, "").strip()
    return Path(raw).expanduser() if raw else DEFAULT_ENV_PATH


@dataclass
class MirrorResult:
    path: Path
    ok: bool
    detail: str = ""


def load() -> dict[str, str]:
    """Return the current secrets dict (or ``{}`` if the file is missing/corrupt)."""
    path = json_path()
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError:
        return {}
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        log.warning("secrets store at %s is not valid JSON; ignoring", path)
        return {}
    if not isinstance(data, dict):
        return {}
    return {str(k): str(v) for k, v in data.items() if isinstance(k, str)}


def save(values: dict[str, str], *, mirror: bool = True) -> MirrorResult:
    """Replace the entire store with ``values``. Returns the mirror result."""
    path = json_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(values, indent=2, sort_keys=True) + "\n"
    fd, tmp = tempfile.mkstemp(prefix=".secrets.", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(payload)
        os.chmod(tmp, 0o600)
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass

    if mirror:
        return write_env_mirror(values)
    return MirrorResult(env_path(), True, "mirror skipped by caller")


def get(name: str, default: str | None = None) -> str | None:
    return load().get(name, default)


def set(name: str, value: str, *, mirror: bool = True) -> MirrorResult:  # noqa: A001
    if not name or not name.replace("_", "").isalnum():
        raise ValueError(f"invalid secret name: {name!r}")
    values = load()
    values[name] = value
    return save(values, mirror=mirror)


def unset(name: str, *, mirror: bool = True) -> MirrorResult:
    values = load()
    if name in values:
        values.pop(name)
        return save(values, mirror=mirror)
    return MirrorResult(env_path(), True, "key not present")


def write_env_mirror(values: dict[str, str]) -> MirrorResult:
    """Best-effort mirror to /etc/hosaka/env. Returns ``ok=False`` if not writable."""
    target = env_path()
    body = _render_env_file(values)
    try:
        target.parent.mkdir(parents=True, exist_ok=True)
    except PermissionError as exc:
        return MirrorResult(target, False, f"cannot create {target.parent}: {exc}")
    fd, tmp = tempfile.mkstemp(prefix=".hosaka-env.", dir=str(target.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(body)
        os.chmod(tmp, 0o640)
        os.replace(tmp, target)
    except PermissionError as exc:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        return MirrorResult(target, False, f"permission denied: {exc}")
    except Exception as exc:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        return MirrorResult(target, False, f"{type(exc).__name__}: {exc}")
    try:
        os.chmod(target, 0o640)
    except OSError:
        pass
    return MirrorResult(target, True, f"wrote {len(values)} entries")


def _render_env_file(values: dict[str, str]) -> str:
    lines = [
        "# /etc/hosaka/env — generated by `hosaka secrets`. Do not edit by hand;",
        "# changes here are overwritten on the next `hosaka secrets set`.",
        "# Edit the source-of-truth at ~/.hosaka/secrets.json instead.",
        "",
    ]
    for name in sorted(values):
        value = values[name]
        lines.append(f"{name}={shlex.quote(value)}")
    lines.append("")
    return "\n".join(lines)


def apply_to_env(*, override: bool = False) -> int:
    """Hydrate ``os.environ`` from the JSON store. Returns count applied."""
    applied = 0
    for name, value in load().items():
        if not override and os.environ.get(name):
            continue
        os.environ[name] = value
        applied += 1
    return applied


def import_from_picoclaw_security() -> tuple[str | None, str | None]:
    """Pull the OpenAI key from ~/.picoclaw/.security.yml if present.

    Returns ``(key, source)`` so callers can report what was imported
    without having to call resolve_api_key themselves.
    """
    try:
        from hosaka.llm.openai_adapter import (
            _load_picoclaw_config,
            _load_picoclaw_security,
            _picoclaw_security_api_key,
        )
    except Exception:  # pragma: no cover - defensive
        return None, None
    cfg = _load_picoclaw_config()
    security = _load_picoclaw_security()
    key = _picoclaw_security_api_key(cfg, security) or None
    if not key:
        return None, None
    return key, "~/.picoclaw/.security.yml"
