#!/usr/bin/env python3
"""gen_user_manual.py — generate docs/manual/ from hosaka.features.yaml.

Tone (per docs/increased_observability.yaml phase 10):
* lowercase, terse, "no wrong way"
* lead with the BALLER COMMAND
* one example, what success looks like, where to look if it didn't work
* hide internal/experimental unless --include-internal

Usage:
    python scripts/gen_user_manual.py [--include-internal] [--out DIR]
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _catalog import REPO_ROOT, load_catalog, features_by_category  # noqa: E402

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/gen_user_manual.py from docs/hosaka.features.yaml. "
    "Do not edit by hand. -->\n\n"
)


def _render_index(catalog: dict, include_internal: bool) -> str:
    lines = [GENERATED_BANNER, "# the manual\n"]
    lines.append("everything you can do, grouped by category. lead with the baller command.\n")
    by_cat = features_by_category(catalog)
    cat_descs = catalog.get("categories", {}) or {}
    for cat in sorted(by_cat):
        desc = cat_descs.get(cat, "")
        lines.append(f"\n## {cat}")
        if desc:
            lines.append(f"_{desc}_\n")
        for f in sorted(by_cat[cat], key=lambda x: x.get("id", "")):
            if not include_internal and f.get("status") in ("experimental",):
                continue
            fid = f["id"]
            name = f.get("name", fid)
            why = (f.get("why_you_care") or "").strip()
            baller = (f.get("baller_command") or "").strip()
            status = f.get("status", "stable")
            badge = "" if status == "stable" else f" *[{status}]*"
            lines.append(f"- **[{name}]({fid}.md)**{badge}")
            if baller:
                lines.append(f"    - `{baller}`")
            if why:
                lines.append(f"    - {why.splitlines()[0]}")
    return "\n".join(lines) + "\n"


def _render_feature(f: dict) -> str:
    fid = f["id"]
    out = [GENERATED_BANNER, f"# {f.get('name', fid)}\n"]
    out.append(f"_status: {f.get('status', 'stable')} · owner: {f.get('owner', '?')} · id: `{fid}`_\n")

    baller = (f.get("baller_command") or "").strip()
    if baller:
        out.append("## the one command\n")
        out.append(f"```\n{baller}\n```\n")

    why = (f.get("why_you_care") or "").strip()
    if why:
        out.append("## why you care\n")
        out.append(f"{why}\n")

    desc = (f.get("description") or "").strip()
    if desc:
        out.append("## what it does\n")
        out.append(f"{desc}\n")

    cmds = f.get("commands") or []
    if cmds:
        out.append("## commands\n")
        for c in cmds:
            out.append(f"- `{c}`")
        out.append("")

    eps = f.get("entrypoints") or []
    if eps:
        out.append("## entrypoints\n")
        for ep in eps:
            t = ep.get("type", "?")
            if t == "http":
                out.append(f"- `{ep.get('method','GET')} {ep.get('path','?')}`")
            elif t == "script":
                out.append(f"- script: `{ep.get('path','?')}`")
            elif t == "doc":
                out.append(f"- doc: `{ep.get('path','?')}`")
            else:
                out.append(f"- {t}: `{ep.get('path','?')}`")
        out.append("")

    fmodes = f.get("failure_modes") or []
    if fmodes:
        out.append("## what success looks like / what failure looks like\n")
        out.append("if it works, it's quiet. if it doesn't, expect one of:\n")
        for fm in fmodes:
            out.append(f"- {fm}")
        out.append("")
        out.append("dig deeper:")
        out.append(f"- `curl -s http://127.0.0.1:8421/api/v1/events?feature_id={fid}&limit=20 | jq`")
        out.append("- `/doctor`")
        out.append("")

    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--include-internal", action="store_true")
    ap.add_argument("--out", default=str(REPO_ROOT / "docs" / "manual"))
    args = ap.parse_args()

    catalog = load_catalog()
    if not catalog.get("features"):
        print("[gen_user_manual] no features found; nothing to generate", file=sys.stderr)
        return 0

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    (out_dir / "index.md").write_text(
        _render_index(catalog, args.include_internal), encoding="utf-8"
    )
    written = 1
    for f in catalog["features"]:
        if not args.include_internal and f.get("status") in ("experimental",):
            # Still write the page so direct links work; just skip on the index.
            pass
        page = out_dir / f"{f['id']}.md"
        page.write_text(_render_feature(f), encoding="utf-8")
        written += 1

    print(f"[gen_user_manual] wrote {written} file(s) to {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
